server:
  port: ${SERVER_PORT:8081}
  address: ${SERVER_ADDRESS:0.0.0.0}
  tomcat:
    accesslog:
      enabled: true
      pattern: '%{yyyy-MM-dd HH:mm:ss.SSS}t %{trace_uuid}r [%I] [%r] [X-AUTH-TOKEN=%{x-auth-token}i] [HTTP CODE=%s] [TIME TAKEN=%D MS] [BYTES SENT=%b BYTE] %a %{User-Agent}i'
  max-http-header-size: 102400

spring:
  application:
    name: api-upload
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

harbor:
  user: ${HARBOR_USER:admin}
  password: ${HARBOR_PWD:admin}
  tmp: ${HARBOR_TAR_TMP:/usr/app/tmp}
  remote: ${HARBOR_REMOTE:http://127.0.0.1}
